name: Archive

on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Upload Archive
        uses: actions/upload-artifact@v2
        with:
          name: Vue 3 TypeScript
          path: |
           templates
           files
           config.json
